const KEY='beirne-proofroom-v1';
const seed=[{id:'PR-001',title:'Make the mobile project captions visible',notes:'People should be able to identify a project without hovering. Done means every card has a readable caption on touch screens.',owner:'Design',priority:'High',status:'Open'},{id:'PR-002',title:'Check the contact journey with a keyboard',notes:'Tab through every field. Confirm labels, validation and the final email preview are understandable.',owner:'Build',priority:'High',status:'In review'},{id:'PR-003',title:'Replace generic project descriptions',notes:'Explain the specific challenge and the choices made. Keep self-initiated work clearly labeled.',owner:'Studio',priority:'Normal',status:'Open'},{id:'PR-004',title:'Respect reduced-motion preferences',notes:'The tree and animated wordmark should become static when reduced motion is requested.',owner:'Build',priority:'Normal',status:'Resolved'}];
const $=s=>document.querySelector(s),statuses=['Open','In review','Resolved'],priorities=['Low','Normal','High'];let issues=structuredClone(seed),filter='all',query='',editing=null;
function valid(data){return Array.isArray(data)&&data.length<=500&&data.every(x=>x&&typeof x.id==='string'&&x.id.length<100&&typeof x.title==='string'&&x.title.trim()&&x.title.length<=120&&typeof x.notes==='string'&&x.notes.length<=3000&&typeof x.owner==='string'&&x.owner.length<=60&&statuses.includes(x.status)&&priorities.includes(x.priority))&&new Set(data.map(x=>x.id)).size===data.length}
try{const saved=localStorage.getItem(KEY);if(saved){const parsed=JSON.parse(saved);if(valid(parsed))issues=parsed;else $('#notice').textContent='Saved data could not be read. Sample workspace loaded.'}}catch{$('#notice').textContent='Browser storage is unavailable. Export your work before leaving.'}
function persist(message){try{localStorage.setItem(KEY,JSON.stringify(issues));$('#notice').textContent=message}catch{$('#notice').textContent=message+' Browser storage is unavailable; export to keep your changes.'}}
function render(){const done=issues.filter(x=>x.status==='Resolved').length;$('#all-count').textContent=issues.length;$('#open-count').textContent=issues.filter(x=>x.status==='Open').length;$('#review-count').textContent=issues.filter(x=>x.status==='In review').length;$('#done-count').textContent=done;$('#active').textContent=issues.length-done;$('#resolved').textContent=done;const pc=issues.length?Math.round(done/issues.length*100):0;$('#progress').value=pc;$('#progress-label').textContent=pc+'% resolved';const visible=issues.filter(x=>(filter==='all'||x.status===filter)&&[x.title,x.notes,x.owner,x.id].join(' ').toLowerCase().includes(query));$('#items').replaceChildren();$('#empty').hidden=visible.length>0;for(const issue of visible){const row=document.createElement('div');row.className='row';const title=document.createElement('button');title.className='row-title';const id=document.createElement('small');id.textContent=issue.id;title.append(id,document.createTextNode(issue.title));title.onclick=()=>open(issue);const owner=document.createElement('span');owner.className='owner';owner.textContent=issue.owner||'Unassigned';const priority=document.createElement('span');priority.className='priority '+issue.priority.toLowerCase();priority.textContent=issue.priority;const status=document.createElement('select');status.setAttribute('aria-label','Status for '+issue.title);for(const s of statuses){const opt=new Option(s,s);status.add(opt)}status.value=issue.status;status.onchange=()=>{issue.status=status.value;persist(issue.id+' moved to '+issue.status+'.');render()};row.append(title,owner,priority,status);$('#items').append(row)}}
function open(issue){editing=issue?.id||null;$('#delete').textContent='Delete feedback';$('#edit-form').reset();$('#dialog-title').textContent=issue?'Edit feedback':'Add feedback';$('#delete').hidden=!issue;for(const name of ['title','notes','owner','priority','status'])if(issue)$('#edit-form').elements[name].value=issue[name];$('#editor').showModal();$('#edit-form').elements.title.focus()}
$('#new').onclick=()=>open();$('#close').onclick=()=>$('#editor').close();$('#edit-form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.currentTarget),title=data.get('title').trim();if(!title){e.currentTarget.elements.title.setCustomValidity('Enter a feedback title.');e.currentTarget.elements.title.reportValidity();return}const item={id:editing||'PR-'+crypto.randomUUID().slice(0,8).toUpperCase(),title,notes:data.get('notes').trim(),owner:data.get('owner').trim(),priority:data.get('priority'),status:data.get('status')};if(editing)issues=issues.map(x=>x.id===editing?item:x);else issues.unshift(item);persist('Feedback saved.');render();$('#editor').close()};$('#edit-form').elements.title.oninput=e=>e.target.setCustomValidity('');$('#delete').onclick=()=>{if($('#delete').textContent!=='Confirm delete'){ $('#delete').textContent='Confirm delete';return }{issues=issues.filter(x=>x.id!==editing);persist('Feedback deleted.');render();$('#editor').close()}};
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()});$('#search').oninput=e=>{query=e.target.value.toLowerCase();render()};
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#export').onclick=()=>{$('#handoff-json').value=JSON.stringify({version:1,exportedAt:new Date().toISOString(),issues},null,2);$('#export-preview').showModal()};$('#close-export').onclick=()=>$('#export-preview').close();$('#save-handoff').onclick=()=>{download('proofroom-handoff.json',$('#handoff-json').value,'application/json');$('#notice').textContent='Download requested. The export preview is also available to copy.'};$('#import').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2e6)throw Error('File is too large.');const data=JSON.parse(await file.text());if(data.version!==1||!valid(data.issues))throw Error('Choose a valid Proofroom handoff.');pendingImport=data.issues;$('#import-message').textContent='Replace the current local workspace with '+data.issues.length+' imported items? Export first if you need to keep the current feedback.';$('#import-confirm').showModal();}catch(error){$('#notice').textContent=error.message||'Could not read that handoff.'}finally{e.target.value=''}};render();

let pendingImport=null;$('#cancel-import').onclick=()=>{$('#import-confirm').close();pendingImport=null};$('#confirm-import').onclick=()=>{if(pendingImport){issues=pendingImport;pendingImport=null;persist('Handoff imported.');render()}$('#import-confirm').close()};

$('#reset-demo').onclick=()=>{if($('#reset-demo').textContent!=='Confirm reset'){ $('#reset-demo').textContent='Confirm reset';$('#notice').textContent='Reset replaces this browser workspace with fictional sample data. Export first to keep your changes.';return}issues=structuredClone(seed);filter='all';query='';$('#search').value='';document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter==='all')));persist('Sample workspace restored.');render();$('#reset-demo').textContent='Reset sample'};
