'use strict';
let receipt=null,chosenFiles=[];
const ruleBox=document.querySelector('#check-rules');
ruleBox.value=JSON.stringify([{id:'page-present',requirement:project.requirements[0]?.id||'R1',file:'index.html',op:'exists'},{id:'no-placeholder',requirement:project.requirements[0]?.id||'R1',file:'index.html',op:'excludes',value:'TODO'}],null,2);
window.clearAutomatedReview=()=>{receipt=null;document.querySelector('#download-receipt').disabled=true;document.querySelector('#auto-results').textContent='No current receipt. Run checks against this version.'};
ruleBox.oninput=window.clearAutomatedReview;
document.querySelector('#check-files').onchange=e=>{chosenFiles=[...e.target.files];window.clearAutomatedReview();document.querySelector('#selected-files').textContent=chosenFiles.map(f=>f.name).join(', ')};
function showReceipt(r,demo){const host=document.querySelector('#auto-results');host.replaceChildren();const title=document.createElement('h3');title.textContent=(demo?'Example only: ':'')+r.summary.passed+' checks passed / '+r.summary.failed+' failed / '+r.summary.notChecked+' requirements not checked';host.append(title);for(const row of r.checks){const article=document.createElement('article'),head=document.createElement('h3'),p=document.createElement('p');head.textContent=row.status.toUpperCase()+' · '+row.id+' · '+row.requirement;p.textContent=row.file+': '+row.detail;article.append(head,p);host.append(article)}for(const row of r.coverage.filter(x=>x.status==='not-checked')){const p=document.createElement('p');p.textContent=row.id+': NOT CHECKED (no rules mapped)';host.append(p)}const limit=document.createElement('p');limit.textContent=r.limits;host.append(limit)}
document.querySelector('#run-checks').onclick=async()=>{const button=document.querySelector('#run-checks');window.clearAutomatedReview();try{if(!ProofroomBrief.inspect(project).approved)throw Error('Approve your current brief before running checks.');if(!chosenFiles.length)throw Error('Select the actual project text files first.');const baseline=ProofroomBrief.snapshot(project),rulesText=ruleBox.value,rules=JSON.parse(rulesText),files=Object.create(null);let size=0;for(const f of chosenFiles){size+=f.size;if(f.size>2000000||size>10000000)throw Error('Use files under 2 MB each and 10 MB total.');if(Object.hasOwn(files,f.name))throw Error('Duplicate filenames: choose unambiguous files.');files[f.name]=await f.text()}button.disabled=true;const result=await ProofroomVerifier.verify({baseline,requirements:project.requirements.map(r=>r.id),rules,files});if(baseline!==ProofroomBrief.snapshot(project)||rulesText!==ruleBox.value)throw Error('The brief or rules changed during review. Run again.');receipt=result;showReceipt(result,false);document.querySelector('#download-receipt').disabled=false}catch(e){document.querySelector('#auto-results').textContent=e.message}finally{button.disabled=false}};
document.querySelector('#demo-checks').onclick=async()=>{window.clearAutomatedReview();try{const result=await ProofroomVerifier.verify({baseline:'Demonstration fixture, not your project',requirements:['demo-1','demo-2'],files:{'index.html':'<h1>TODO</h1>'},rules:[{id:'has-page',requirement:'demo-1',file:'index.html',op:'exists'},{id:'no-placeholder',requirement:'demo-1',file:'index.html',op:'excludes',value:'TODO'}]});showReceipt(result,true)}catch(e){document.querySelector('#auto-results').textContent=e.message}};
document.querySelector('#download-receipt').onclick=()=>{if(receipt)download('proofroom-check-receipt.json',JSON.stringify(receipt,null,2),'application/json')};
