const {test}=require('node:test');const a=require('node:assert/strict');const B=require('./brief-core.js');
function fixture(){return{version:1,name:'Proofroom',goal:'Keep a product aligned with its approved brief.',audience:'Solo builders using coding agents',requirements:[{id:'motion',text:'Only people and trees move',kind:'requirement',verification:'test',acceptance:'Inspect active animations; no heading or button animations.',dependsOn:[],constraint:{key:'motion',value:'people-and-trees'}},{id:'art',text:'People fit the town',kind:'requirement',verification:'human',acceptance:'Review scale, linework and perspective against town artwork.',dependsOn:['motion']},{id:'no-login',text:'Demo needs no login',kind:'exclusion',verification:'test',acceptance:'Complete core flow in a signed-out browser.',dependsOn:[]}],questions:[{id:'who',text:'Who is the first user?',answer:'Solo builders'}]}}
test('unapproved drafts cannot export assignments',()=>{a.throws(()=>B.task(fixture(),['art'],'Improve illustration'),/Approve/)});
test('open decisions block approval',()=>{const p=fixture();p.questions[0].answer='';a.equal(B.inspect(p).ready,false);a.throws(()=>B.approve(p,'Ethan'),/Resolve/)});
test('explicit conflicting constraints block approval',()=>{const p=fixture();p.requirements[1].constraint={key:'Motion',value:'animate-everything'};a.equal(B.inspect(p).conflicts.length,1);a.throws(()=>B.approve(p,'Ethan'))});
test('changed requirement invalidates approval and previous assignment',()=>{const p=B.approve(fixture(),'Ethan'),t=B.task(p,['art'],'Improve artwork');const req=structuredClone(p.requirements);req[0].text='Move everything';const changed=B.update(p,{requirements:req});a.equal(B.inspect(changed).approved,false);a.throws(()=>B.review(changed,t,[]),/stale/);a.throws(()=>B.markdown(changed,t),/stale/)});
test('tampered approval cannot be reused after direct edits',()=>{const p=B.approve(fixture(),'Ethan');p.goal='Different goal';a.equal(B.inspect(p).approved,false)});
test('task brings transitive dependencies and all hard project guardrails',()=>{const p=B.approve(fixture(),'Ethan'),t=B.task(p,['art'],'Improve artwork');a.deepEqual(t.requirements.map(x=>x.id),['motion','art']);a.deepEqual(t.guardrails.map(x=>x.id),['no-login']);a.match(B.markdown(p,t),/no-login/)});
test('missing evidence is unverified, never passed',()=>{const p=B.approve(fixture(),'Ethan');const r=B.review(p,B.task(p,['art'],'Draw'),[]);a.equal(r.counts.unverified,3);a.equal(r.counts.attested,0)});
test('reported success is only attested and failure remains a conflict',()=>{const p=B.approve(fixture(),'Ethan');const r=B.review(p,B.task(p,['art'],'Draw'),[{id:'art',outcome:'met',note:'Scale checked visually',reference:'screenshot.png',reviewer:'Ethan'},{id:'motion',outcome:'failed',note:'Heading animates',reference:'animation audit',reviewer:'Ethan'}]);a.deepEqual(r.counts,{attested:1,conflict:1,unverified:1});a.match(r.disclaimer,/not independently/)});
test('empty references, duplicate evidence, unknown evidence are rejected',()=>{const p=B.approve(fixture(),'Ethan'),t=B.task(p,['art'],'Draw'),e={id:'art',outcome:'met',note:'Seen',reference:'capture',reviewer:'Ethan'};a.throws(()=>B.review(p,t,[{...e,reference:''}]));a.throws(()=>B.review(p,t,[e,e]));a.throws(()=>B.review(p,t,[{...e,id:'fake'}]))});
test('cycles and dangling dependencies rejected',()=>{const p=fixture();p.requirements[0].dependsOn=['art'];a.throws(()=>B.validate(p),/cycle/);p.requirements[0].dependsOn=['missing'];a.throws(()=>B.validate(p),/dependency/)});
test('malformed imports fail closed',()=>{for(const s of ['null','[]','{}','not json','{"version":2}'])a.throws(()=>B.parse(s));const p=fixture();p.requirements.push(p.requirements[0]);a.throws(()=>B.validate(p),/Duplicate/);a.throws(()=>B.parse('x'.repeat(1000001)),/large/)});
test('unknown fields and oversized values rejected',()=>{a.throws(()=>B.validate({...fixture(),admin:true}),/Unknown/);a.throws(()=>B.validate({...fixture(),name:'x'.repeat(161)}));const p=fixture();p.requirements[0].verification='magic';a.throws(()=>B.validate(p))});
test('round trip preserves approved state and does not mutate inputs',()=>{const p=fixture(),before=JSON.stringify(p),approved=B.approve(p,'Ethan');a.equal(JSON.stringify(p),before);a.equal(B.inspect(B.parse(JSON.stringify(approved))).approved,true);B.task(approved,['art'],'Draw');a.equal(JSON.stringify(p),before)});
test('all nonempty requirement selections keep every hard requirement',()=>{const p=B.approve(fixture(),'Ethan');for(let bits=1;bits<8;bits++){const ids=p.requirements.filter((_,i)=>bits&(1<<i)).map(r=>r.id);const t=B.task(p,ids,'Work');a.equal(new Set([...t.requirements,...t.guardrails].map(r=>r.id)).size,3)}});
test('empty and unknown task selections rejected',()=>{const p=B.approve(fixture(),'Ethan');a.throws(()=>B.task(p,[],'Work'));a.throws(()=>B.task(p,['unknown'],'Work'))});
test('blank brief cannot be approved',()=>{const p=fixture();p.requirements=[];a.equal(B.inspect(p).ready,false);a.throws(()=>B.approve(p,'Ethan'))});
test('modified task cannot drop guardrails or rewrite acceptance criteria',()=>{const p=B.approve(fixture(),'Ethan'),t=B.task(p,['art'],'Draw');t.guardrails=[];a.throws(()=>B.review(p,t,[]),/modified/);const u=B.task(p,['art'],'Draw');u.requirements[0].acceptance='Trust me';a.throws(()=>B.markdown(p,u),/modified/)});
