'use strict';
(function(){
 const get=id=>document.getElementById(id),storeKey='proofroom-sessions-v1';let sessions=[];
 try{sessions=JSON.parse(localStorage.getItem(storeKey)||'[]');if(!Array.isArray(sessions))sessions=[];sessions=sessions.slice(-20)}catch{}
 function draw(){const host=get('session-history');host.replaceChildren();for(const s of [...sessions].reverse()){const row=document.createElement('article');const title=document.createElement('h3');title.textContent=s.project||'Review session';const p=document.createElement('p');p.textContent=(s.source||'Imported')+' · '+s.createdAt+' · '+(s.ok===true?'Configured checks passed':'Blocked / incomplete');row.append(title,p);const list=document.createElement('ul');for(const c of s.coverage||[]){const li=document.createElement('li');li.textContent=c.id+': '+c.status;list.append(li)}row.append(list);host.append(row)}}
 window.saveReviewSession=r=>{sessions.push({...r,source:r.source||'This browser'});sessions=sessions.slice(-20);try{localStorage.setItem(storeKey,JSON.stringify(sessions));draw()}catch{get('hosted-status').textContent='Session storage unavailable. Download the receipt.'}};
 get('receipt-file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>2000000)throw Error('Receipt exceeds 2 MB');const r=JSON.parse(await f.text());if(r.version!==1||!Array.isArray(r.coverage)||r.coverage.length>150||typeof r.briefSha256!=='string'||!Array.isArray(r.checks))throw Error('Unsupported receipt');if(r.coverage.some(x=>!x||typeof x.id!=='string'||!['checks-passed','not-checked','fail'].includes(x.status)))throw Error('Invalid receipt coverage');r.ok=r.changedDuringRun?.length?false:r.coverage.length>0&&r.coverage.every(x=>x.status==='checks-passed');r.source='Imported receipt (not authenticated)';window.saveReviewSession(r);get('hosted-status').textContent='Receipt saved. Importing does not independently verify its contents.'}catch(err){get('hosted-status').textContent=err.message}finally{e.target.value=''}};
 get('connect-github').onclick=async()=>{const button=get('connect-github');button.disabled=true;const host=get('github-runs');host.replaceChildren();try{const value=get('github-repo').value.trim().replace(/^https:\/\/github.com\//,'').replace(/\/$/,'');if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(value))throw Error('Enter owner/repository or its GitHub URL');get('hosted-status').textContent='Reading public GitHub verification runs…';const res=await fetch('https://api.github.com/repos/'+value+'/actions/workflows/proofroom.yml/runs?per_page=5',{headers:{Accept:'application/vnd.github+json'}});if(!res.ok)throw Error(res.status===404?'No public proofroom.yml workflow found. Follow the setup guide below.':res.status===403?'GitHub rate limit or access restriction. Open the runs on GitHub.':'GitHub returned '+res.status);const data=await res.json();for(const r of data.workflow_runs||[]){const row=document.createElement('article'),a=document.createElement('a'),p=document.createElement('p');a.href='https://github.com/'+value+'/actions/runs/'+r.id;a.target='_blank';a.rel='noopener';a.textContent=(r.conclusion||r.status)+' · '+r.head_sha.slice(0,8);p.textContent=r.created_at+' · '+r.name;row.append(a,p);host.append(row)}const link=document.createElement('a');link.href='https://github.com/'+value+'/actions/workflows/proofroom.yml';link.target='_blank';link.rel='noopener';link.textContent='Run verification / download receipts on GitHub';host.append(link);get('hosted-status').textContent='GitHub-reported workflow status. Inspect the run summary and receipt for exact checks. Public repositories only; no credentials are collected.'}catch(err){get('hosted-status').textContent=err.message}finally{button.disabled=false}};
 draw();
})();
