(function(root,factory){const model=factory();if(typeof module==='object'&&module.exports)module.exports=model;else root.ProofroomModel=model})(typeof globalThis!=='undefined'?globalThis:this,function(){
 const nodes={
  services:{title:'Services & durations',kind:'foundation',why:'Customers need to know what they can book and how long it takes.',questions:['Which services, durations and buffers should be offered?'],assumption:'One business with a single service catalogue.'},
  request:{title:'Booking request',kind:'foundation',deps:['services'],why:'Collect a preferred time and contact details without promising a reserved slot.',questions:['What information is needed to approve a request?'],assumption:'The lean version uses manual approval, not immediate booking.'},
  inbox:{title:'Request inbox',kind:'foundation',deps:['request'],why:'Someone needs to review, approve or decline each request.',questions:['Who checks requests, and how quickly should they respond?'],assumption:'A designated operator manages requests.'},
  confirmation:{title:'Confirmation message',kind:'foundation',deps:['inbox'],why:'Customers need an unambiguous answer after the operator approves a request.',questions:['How will customers receive an approval or rejection?'],assumption:'A confirmation can be sent manually in the lean version.'},
  privacy:{title:'Contact data & retention',kind:'foundation',deps:[],why:'Contact details need a defined purpose, access policy and deletion process.',questions:['Which contact data must be kept, who can access it, and for how long?'],assumption:'This planner stores no customer booking data.'},
  calendar:{title:'Availability calendar',kind:'system',deps:['services'],why:'Booking features need a shared source of available times, working hours and blocked periods.',questions:['Which calendar is authoritative, and how are breaks and closures recorded?'],assumption:'Availability rules must be agreed before implementation.'},
  reservations:{title:'Slot reservation & conflicts',kind:'system',deps:['calendar'],why:'Two customers must not reserve the same capacity. The final availability check needs to be atomic.',questions:['When is a slot held, and when does that hold expire?'],assumption:'A server-side reservation system would be needed; this demo does not provide one.'},
  records:{title:'Booking records',kind:'system',deps:['privacy'],why:'Automated changes need a persistent booking ID and a clear booking state.',questions:['Which booking states can operators and customers change?'],assumption:'Real booking records would live in a backend, not this planner.'},
  delivery:{title:'Message delivery',kind:'system',deps:['privacy'],why:'Automated messages require a channel, templates and handling for failed delivery.',questions:['Email or SMS, and what should happen if delivery fails?'],assumption:'A delivery provider and its costs are not selected here.'},
  payment:{title:'Payment provider',kind:'system',deps:['records'],why:'Taking money requires a payment provider and a defined payment flow.',questions:['Which provider, currency and payment methods are supported?'],assumption:'No card data or payments are processed by this demo.'},
  paymentEvents:{title:'Payment events & retries',kind:'system',deps:['payment','reservations'],why:'Payment success, failure and retries must agree with slot and booking states.',questions:['What happens if payment succeeds after the slot hold expires?'],assumption:'Duplicate payment events must be handled safely.'},
  refunds:{title:'Deposit & refund rules',kind:'decision',deps:['payment'],why:'Customers and operators need to know what is charged and when a refund applies.',questions:['Is the deposit fixed or a percentage? When is it refundable?'],assumption:'Refund terms require the business owner’s decision.'},
  changeRules:{title:'Cancellation & change rules',kind:'decision',deps:['records'],why:'Rescheduling and reminders need a consistent rule for changes and cancellations.',questions:['How close to the appointment can a customer cancel or move it?'],assumption:'The business chooses the policy; the planner does not recommend a legal policy.'},
  secureLink:{title:'Secure manage-booking link',kind:'system',deps:['records','delivery'],why:'Customers need a secure way to change their own booking without accessing anyone else’s.',questions:['How long should management links stay valid?'],assumption:'A time-limited link is assumed instead of requiring an account.'},
  scheduler:{title:'Scheduled jobs & retries',kind:'system',deps:['records','delivery'],why:'Reminders need reliable timing, retry rules and cancellation when the booking changes.',questions:['When should reminders run, and what is the retry policy?'],assumption:'A background scheduling service would be required.'},
  roster:{title:'Staff roster & capacity',kind:'system',deps:['calendar','records'],why:'Multiple people bring individual hours, skills, leave and service capacity.',questions:['Can any staff member perform any service?'],assumption:'Staff scheduling is separate from customer accounts.'},
  access:{title:'Operator access controls',kind:'system',deps:['privacy'],why:'Different staff need appropriate permissions to view or change bookings.',questions:['Who may change schedules, issue refunds or export customer data?'],assumption:'Authentication and role checks would be implemented server-side.'},
  queue:{title:'Waitlist & offer expiry',kind:'system',deps:['reservations','delivery','records'],why:'A freed slot needs a fair offer order and an expiry time before it can go to someone else.',questions:['Who gets the first offer, and how long do they have to accept?'],assumption:'Customers explicitly opt in to the waitlist.'},
  identity:{title:'Customer sign-in & recovery',kind:'system',deps:['privacy'],why:'Accounts need secure sign-in, recovery and session management.',questions:['How do customers sign in, recover access and delete their account?'],assumption:'No authentication provider is selected.'},
  history:{title:'Private booking history',kind:'system',deps:['identity','records'],why:'Each customer must see only their own past and upcoming bookings.',questions:['How are old bookings linked to a new customer account?'],assumption:'Ownership checks are required for every record.'}
 };
 const features=[
 {id:'instant',title:'Instant booking',short:'Reserve a real slot, right away.',deps:['reservations','records','delivery'],tradeoff:'Less manual approval, but availability and booking states must stay in sync.'},
 {id:'deposits',title:'Take a deposit',short:'Collect part of the price up front.',deps:['paymentEvents','refunds','delivery'],tradeoff:'Adds payment failure, refund and slot-hold decisions, not just a payment button.'},
 {id:'reschedule',title:'Let customers reschedule',short:'Move a booking without a phone call.',deps:['secureLink','changeRules','reservations'],tradeoff:'Changes must respect capacity, cut-off times and any paid deposit.'},
 {id:'reminders',title:'Send reminders',short:'A timely nudge before the appointment.',deps:['scheduler','changeRules'],tradeoff:'Adds timed delivery and cancellation logic; reminders do not guarantee attendance.'},
 {id:'staff',title:'Add multiple staff',short:'Different people, hours and skills.',deps:['roster','access','reservations'],tradeoff:'A single calendar becomes a capacity and permissions problem.'},
 {id:'waitlist',title:'Fill cancelled slots',short:'Offer openings to waiting customers.',deps:['queue','changeRules'],tradeoff:'Needs an offer order, an expiry window and protection against double booking.'},
 {id:'accounts',title:'Customer accounts',short:'Keep a private booking history.',deps:['history','secureLink'],tradeoff:'Convenient repeat visits bring identity, recovery and account-lifecycle work.'}
 ];
 const base=['services','request','inbox','confirmation','privacy'];
 function normalize(ids){return Array.isArray(ids)?[...new Set(ids.filter(id=>features.some(f=>f.id===id)))]:[]}
 function plan(ids){const chosen=normalize(ids);const included=new Set();const reasons={};function add(id,reason,path=[]){if(!nodes[id])throw Error('Unknown dependency '+id);if(path.includes(id))throw Error('Dependency cycle');included.add(id);(reasons[id]??=new Set()).add(reason);for(const dep of nodes[id].deps||[])add(dep,reason,[...path,id])}base.forEach(id=>add(id,'Lean starting point'));features.filter(f=>chosen.includes(f.id)).forEach(f=>f.deps.forEach(id=>add(id,f.title)));return {selected:chosen,items:Object.keys(nodes).filter(id=>included.has(id)).map(id=>({id,...nodes[id],reasons:[...reasons[id]]})),added:[...included].filter(id=>!base.includes(id)),questions:[...new Set([...included].flatMap(id=>nodes[id].questions)),...(chosen.includes("deposits")&&chosen.includes("reschedule")?["Does the deposit transfer when a booking moves, and how are price differences handled?"]:[])]}}
 function brief(ids,note=''){const result=plan(ids);return {version:1,product:'Proofroom',scenario:'Appointment-booking website',selectedFeatures:features.filter(f=>result.selected.includes(f.id)).map(f=>({id:f.id,title:f.title,tradeoff:f.tradeoff})),foundation:base.map(id=>nodes[id].title),additionalWork:result.items.filter(x=>!base.includes(x.id)).map(({id,title,why,reasons,assumption})=>({id,title,why,reasons,assumption})),openQuestions:result.questions,projectNote:String(note).slice(0,2000),boundary:'Illustrative scope model, not an implementation, quote, timeline or exhaustive requirements audit.'}}
 function markdown(ids,note=''){const b=brief(ids,note);return ['# Booking project brief','',b.boundary,'','## Selected features',...(b.selectedFeatures.length?b.selectedFeatures.map(f=>'- '+f.title+': '+f.tradeoff):['- Lean booking requests with manual approval.']),'','## Foundation',...b.foundation.map(x=>'- '+x),'','## Additional work',...(b.additionalWork.length?b.additionalWork.map(x=>'- '+x.title+'\n  '+x.why+'\n  Needed by: '+x.reasons.join(', ')+'\n  Assumption: '+x.assumption):['- None beyond the lean foundation.']),'','## Open questions',...b.openQuestions.map(x=>'- '+x),'','## Your context',b.projectNote||'Not provided.'].join('\n')}
 return {nodes,features,base,normalize,plan,brief,markdown};
});
