#!/usr/bin/env node
'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),{spawn}=require('node:child_process'),crypto=require('node:crypto');
const B=require('./brief-core.js'),V=require('./verifier.js');
const digest=x=>crypto.createHash('sha256').update(x).digest('hex');
async function within(root,name){if(typeof name!=='string'||path.isAbsolute(name)||name.split(/[\\/]/).includes('..'))throw Error('Unsafe project path');const target=path.resolve(root,name);if(target!==root&&!target.startsWith(root+path.sep))throw Error('Path escapes project');const actual=await fs.realpath(target);if(actual!==root&&!actual.startsWith(root+path.sep))throw Error('Symlink escapes project');return actual}
function execute(args,cwd,timeout){return new Promise(resolve=>{let child,stdout='',stderr='',reason='',finished=false;const stop=why=>{reason=why;if(process.platform==='win32'&&child.pid){spawn('taskkill',['/pid',String(child.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'})}else if(child.pid){try{process.kill(-child.pid,'SIGKILL')}catch{child.kill('SIGKILL')}}};try{child=spawn(process.execPath,args,{cwd,shell:false,windowsHide:true,detached:process.platform!=='win32',env:{...process.env,NODE_OPTIONS:''},stdio:['ignore','pipe','pipe']})}catch(e){return resolve({exitCode:null,stdout,stderr:e.message,reason:'spawn-error'})}const timer=setTimeout(()=>stop('timeout'),timeout);const finish=(code,error)=>{if(finished)return;finished=true;clearTimeout(timer);resolve({exitCode:code,stdout,stderr:stderr+(error||''),reason})};child.on('error',e=>finish(null,e.message));for(const [stream,key]of [[child.stdout,'stdout'],[child.stderr,'stderr']])stream.on('data',buf=>{if(key==='stdout')stdout+=buf.toString();else stderr+=buf.toString();if(stdout.length+stderr.length>200000){stdout=stdout.slice(0,100000);stderr=stderr.slice(0,100000);stop('output-limit')}});child.on('close',code=>finish(code))})}
async function run({root,config='proofroom.config.json',allowRun=false}){
 root=await fs.realpath(root);const configPath=await within(root,config),configText=await fs.readFile(configPath,'utf8'),c=JSON.parse(configText);
 if(c.version!==1||!Array.isArray(c.rules)||!Array.isArray(c.tests)||c.tests.length>100)throw Error('Invalid runner configuration');
 const briefPath=await within(root,c.brief),brief=B.parse(await fs.readFile(briefPath,'utf8'));if(!B.inspect(brief).approved)throw Error('Brief is not approved');
 const ids=brief.requirements.map(r=>r.id);V.validate(c.rules,ids);const used=new Set(c.rules.map(r=>r.id));for(const t of c.tests){if(!t||typeof t.id!=='string'||used.has(t.id)||!ids.includes(t.requirement)||!Array.isArray(t.args)||!t.args.length||t.args.some(x=>typeof x!=='string')||!Number.isInteger(t.timeoutMs)||t.timeoutMs<50||t.timeoutMs>300000)throw Error('Invalid test definition');used.add(t.id)}
 const files=Object.create(null);for(const r of c.rules){try{const f=await within(root,r.file);const stat=await fs.stat(f);if(!stat.isFile()||stat.size>2000000)throw Error('File exceeds 2 MB');files[r.file]=await fs.readFile(f,'utf8')}catch(e){if(e.code==='ENOENT')continue;throw e}}
 const report=await V.verify({baseline:B.snapshot(brief),requirements:ids,rules:c.rules,files});report.configSha256=digest(configText);report.project=brief.name;report.tests=[];
 let revision=null;try{revision=(await fs.readFile(path.join(root,'.git','HEAD'),'utf8')).trim()}catch{}report.gitHead=revision;
 for(const t of c.tests){if(!allowRun){report.tests.push({id:t.id,requirement:t.requirement,status:'not-run',reason:'Explicit --allow-run is required'});continue}const result=await execute(t.args,root,t.timeoutMs);report.tests.push({id:t.id,requirement:t.requirement,args:t.args,status:result.exitCode===0&&!result.reason?'pass':'fail',...result})}
 // Detect changes to the exact contract and checked source during the session.
 report.changedDuringRun=[];if(digest(await fs.readFile(configPath,'utf8'))!==report.configSha256)report.changedDuringRun.push(config);if(B.snapshot(B.parse(await fs.readFile(briefPath,'utf8')))!==B.snapshot(brief))report.changedDuringRun.push(c.brief);for(const [f,hash]of Object.entries(report.files)){try{if(await V.sha(await fs.readFile(await within(root,f),'utf8'))!==hash)report.changedDuringRun.push(f)}catch{report.changedDuringRun.push(f)}}
 report.coverage=ids.map(id=>{const all=[...report.checks,...report.tests].filter(t=>t.requirement===id);return{id,status:!all.length?'not-checked':all.some(t=>t.status==='fail')?'fail':all.some(t=>t.status==='not-run')?'not-checked':'checks-passed',checks:all.length}});
 report.ok=!report.changedDuringRun.length&&report.coverage.every(x=>x.status==='checks-passed');report.limits='Local Node test commands execute with your user permissions, not in a sandbox. Only run trusted projects. Hosted runs should use isolated runners without secrets. Passed checks prove listed assertions only, not general AI correctness. Uncovered requirements block a complete pass.';return report;
}
async function cli(){const args=process.argv.slice(2),root=path.resolve(args[0]||'.'),out=args.includes('--out')?args[args.indexOf('--out')+1]:'proofroom-report.json';const report=await run({root,allowRun:args.includes('--allow-run')});await fs.writeFile(path.resolve(out),JSON.stringify(report,null,2));console.log(JSON.stringify({ok:report.ok,coverage:report.coverage,report:path.resolve(out)},null,2));process.exitCode=report.ok?0:1}
if(require.main===module)cli().catch(e=>{console.error(e.message);process.exitCode=2});module.exports={run,within,execute};
