const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),B=require('./brief-core.js'),{run}=require('./runner.cjs');
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'proofroom-run-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const brief=B.approve({version:1,name:'Test',goal:'Validate a feature',audience:'Builders',requirements:[{id:'R1',text:'Calculation is correct',kind:'requirement',verification:'test',acceptance:'Actual assertion exits zero',dependsOn:[]}],questions:[]},'Test owner');await fs.writeFile(path.join(root,'brief.json'),JSON.stringify(brief));const config={version:1,brief:'brief.json',rules:[],tests:[{id:'unit',requirement:'R1',args:['-e','require("node:assert/strict").equal(2+2,4)'],timeoutMs:2000}]};await fs.writeFile(path.join(root,'proofroom.config.json'),JSON.stringify(config));return{root,config,save:()=>fs.writeFile(path.join(root,'proofroom.config.json'),JSON.stringify(config))}}
test('real passing assertion generates complete pass',async t=>{const f=await fixture(t);const r=await run({root:f.root,allowRun:true});a.equal(r.ok,true);a.equal(r.tests[0].exitCode,0)});
test('broken behavior produces nonzero test and blocked report',async t=>{const f=await fixture(t);f.config.tests[0].args=['-e','require("node:assert/strict").equal(2+2,5)'];await f.save();const r=await run({root:f.root,allowRun:true});a.equal(r.ok,false);a.equal(r.tests[0].status,'fail')});
test('no authorization means no commands execute',async t=>{const f=await fixture(t);const r=await run({root:f.root});a.equal(r.ok,false);a.equal(r.tests[0].status,'not-run')});
test('hanging process is terminated and never passes',async t=>{const f=await fixture(t);f.config.tests[0].args=['-e','setInterval(()=>{},100)'];f.config.tests[0].timeoutMs=100;await f.save();const r=await run({root:f.root,allowRun:true});a.equal(r.ok,false);a.equal(r.tests[0].reason,'timeout')});
test('missing coverage blocks completion',async t=>{const f=await fixture(t);f.config.tests=[];await f.save();a.equal((await run({root:f.root,allowRun:true})).ok,false)});
test('paths cannot escape root',async t=>{const f=await fixture(t);f.config.brief='../brief.json';await f.save();await a.rejects(run({root:f.root}),/Unsafe/)});
test('changed checked source is detected',async t=>{const f=await fixture(t);await fs.writeFile(path.join(f.root,'source.txt'),'original');f.config.rules=[{id:'file',requirement:'R1',file:'source.txt',op:'contains',value:'original'}];f.config.tests[0].args=['-e','require("node:fs").writeFileSync("source.txt","changed")'];await f.save();const r=await run({root:f.root,allowRun:true});a.equal(r.ok,false);a.deepEqual(r.changedDuringRun,['source.txt'])});
