(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ProofroomVerifier=api;})(globalThis,function(){
 'use strict';
 const ops=['exists','contains','excludes','jsonEquals'];
 function path(p){if(typeof p!=='string'||!p||p.length>500||p.startsWith('/')||p.includes('\\')||p.split('/').some(x=>!x||x==='.'||x==='..')||p.includes(':'))throw Error('Use a relative file path with forward slashes');return p}
 function validate(rules,ids){if(!Array.isArray(rules)||rules.length>200)throw Error('Provide at most 200 checks');const seen=new Set();return rules.map(r=>{if(!r||typeof r!=='object'||Object.keys(r).some(k=>!['id','requirement','file','op','value','pointer'].includes(k)))throw Error('Invalid check fields');if(typeof r.id!=='string'||!r.id||seen.has(r.id))throw Error('Checks need unique IDs');seen.add(r.id);if(!ids.includes(r.requirement))throw Error('Unknown requirement: '+r.requirement);if(!ops.includes(r.op))throw Error('Unsupported operation');path(r.file);if(['contains','excludes'].includes(r.op)&&(typeof r.value!=='string'||!r.value||r.value.length>10000))throw Error('Text checks need a nonempty literal value');if(r.op==='jsonEquals'&&(typeof r.pointer!=='string'||(r.pointer!==''&&!r.pointer.startsWith('/'))||!Object.hasOwn(r,'value')))throw Error('JSON check needs a pointer and value');return JSON.parse(JSON.stringify(r))})}
 async function sha(value){const bytes=new TextEncoder().encode(value);const digest=await globalThis.crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
 function equal(a,b){if(a===b)return true;if(!a||!b||typeof a!=='object'||typeof b!=='object'||Array.isArray(a)!==Array.isArray(b))return false;const ka=Object.keys(a),kb=Object.keys(b);return ka.length===kb.length&&ka.every(k=>Object.hasOwn(b,k)&&equal(a[k],b[k]))}
 async function verify({baseline,requirements,rules,files}){if(typeof baseline!=='string'||!Array.isArray(requirements)||!files||typeof files!=='object')throw Error('Invalid verification input');rules=validate(rules,requirements);const hashes={},checks=[];for(const r of rules){let status='fail',detail='File not provided';if(Object.hasOwn(files,r.file)){const content=files[r.file];if(typeof content!=='string'||content.length>2000000)throw Error('File must be text under 2 MB');hashes[r.file]=await sha(content);try{if(r.op==='exists'){status='pass';detail='File present in the selected snapshot'}if(r.op==='contains'||r.op==='excludes'){const found=content.includes(r.value);status=(r.op==='contains'?found:!found)?'pass':'fail';detail='Literal text '+(found?'found':'not found')}if(r.op==='jsonEquals'){let value=JSON.parse(content);for(const part of r.pointer===''?[]:r.pointer.slice(1).split('/').map(x=>x.replace(/~1/g,'/').replace(/~0/g,'~'))){if(value===null||typeof value!=='object'||!Object.hasOwn(value,part))throw Error('JSON pointer not found');value=value[part]}status=equal(value,r.value)?'pass':'fail';detail='JSON value '+(status==='pass'?'matches':'does not match')}}catch(e){detail=e.message}}checks.push({...r,status,detail})}
 const coverage=requirements.map(id=>{const rows=checks.filter(r=>r.requirement===id);return{id,status:!rows.length?'not-checked':rows.some(r=>r.status==='fail')?'fail':'checks-passed',checks:rows.length}});return{version:1,createdAt:new Date().toISOString(),briefSha256:await sha(baseline),rulesSha256:await sha(JSON.stringify(rules)),files:hashes,checks,coverage,summary:{passed:checks.filter(r=>r.status==='pass').length,failed:checks.filter(r=>r.status==='fail').length,notChecked:coverage.filter(r=>r.status==='not-checked').length},limits:'Only the listed file assertions were checked. Passing checks do not prove the full requirement, running behavior, security, design quality or agent compliance. Receipt hashes bind this report to the supplied text snapshots; they are not a trusted signature.'}}
 return{validate,verify,sha};
});
