'use strict';
const B=ProofroomBrief,$=s=>document.querySelector(s),KEY='proofroom-brief-v1';
const example={version:1,name:'Proofroom',goal:'Help solo builders give coding agents a clear product brief and review the result against it.',audience:'Solo builders working across multiple AI coding sessions',requirements:[{id:'R1',text:'Only people and trees animate',kind:'requirement',verification:'test',acceptance:'Inspect the active animations. No headings, buttons or buildings move.',dependsOn:[],constraint:{key:'animation',value:'people-and-trees'}},{id:'R2',text:'People visually belong in the illustrated town',kind:'requirement',verification:'human',acceptance:'Compare character scale, linework, palette and perspective with the town.',dependsOn:['R1']},{id:'R3',text:'The core demo works without an account',kind:'exclusion',verification:'test',acceptance:'Complete brief, task and review flows in a signed-out browser.',dependsOn:[]}],questions:[{id:'Q1',text:'What is outside this first release?',answer:'No autonomous code execution, repository integration or AI provider.'},{id:'Q2',text:'What would make this useful enough to keep using?',answer:''}]};
let project=structuredClone(example),pack=null,evidence=[];
try{const saved=localStorage.getItem(KEY);if(saved)project=B.parse(saved)}catch{$('#notice').textContent='Saved brief could not be read. Your stored copy has not been overwritten. Export it before making changes.'}
function notice(t){$('#notice').textContent=t}
function save(){try{localStorage.setItem(KEY,JSON.stringify(project))}catch{notice('Local saving is unavailable. Download your brief to keep it.')}}
function run(fn){try{fn()}catch(e){notice(e.message)}}
function changed(next){project=next;pack=null;evidence=[];save();render();notice('Saved locally. Changes require a fresh approval and task packet.')}
function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x}
function button(text,fn){const b=el('button',text);b.type='button';b.onclick=()=>run(fn);return b}
function render(){
 $('#name').value=project.name;$('#goal').value=project.goal;$('#audience').value=project.audience;
 const state=B.inspect(project);$('#brief-status').textContent=state.approved?'Approved by '+project.approval.by:state.ready?'Ready for your approval':'Draft: decisions need attention';
 $('#issues').replaceChildren(...[...state.missing,...state.unanswered.map(q=>'Unanswered: '+q.text),...state.conflicts.map(c=>c.message+' ('+c.ids.join(', ')+')')].map(t=>el('p',t)));
 const rows=$('#requirements');rows.replaceChildren();
 for(const r of project.requirements){const row=el('article',undefined,'brief-row');row.append(el('h3',r.id+' · '+r.text),el('p',r.kind+' / '+(r.verification==='human'?'Human review':'Executable test')),el('p',r.acceptance));if(r.dependsOn.length)row.append(el('p','Depends on '+r.dependsOn.join(', ')));if(r.constraint)row.append(el('p',r.constraint.key+' = '+r.constraint.value));row.append(button('Edit',()=>{for(const k of ['id','text','kind','verification','acceptance'])$('#r-'+k).value=r[k];$('#r-deps').value=r.dependsOn.join(', ');$('#r-key').value=r.constraint?.key||'';$('#r-value').value=r.constraint?.value||'';$('#r-id').readOnly=true;$('#requirement-form').closest('details').open=true;$('#requirement-form').scrollIntoView({block:'center'});$('#r-text').focus()}),button('Remove',()=>{if(project.requirements.some(x=>x.dependsOn.includes(r.id)))throw Error('Remove its dependent links first.');changed(B.update(project,{requirements:project.requirements.filter(x=>x.id!==r.id)}))}));rows.append(row)}
 const qs=$('#questions');qs.replaceChildren();for(const q of project.questions){const label=el('label',q.text),input=el('textarea');input.value=q.answer;input.maxLength=4000;input.rows=2;input.dataset.question=q.id;label.append(input);qs.append(label)}
 const picks=$('#task-picks');picks.replaceChildren();for(const r of project.requirements){const l=el('label',undefined,'pick'),i=el('input');i.type='checkbox';i.value=r.id;i.checked=true;l.append(i,document.createTextNode(r.id+' · '+r.text));picks.append(l)}
 $('#approval').disabled=!state.ready;$('#make-task').disabled=!state.approved;$('#task-preview').value=pack?B.markdown(project,pack):'';$('#review-rows').replaceChildren();$('#review-result').textContent='No review yet. Missing evidence is unverified.';$('#task-download').disabled=!pack;
}
$('#project-form').onsubmit=e=>{e.preventDefault();run(()=>changed(B.update(project,{name:$('#name').value,goal:$('#goal').value,audience:$('#audience').value})))};
$('#requirement-form').onsubmit=e=>{e.preventDefault();run(()=>{const r={id:$('#r-id').value,text:$('#r-text').value,kind:$('#r-kind').value,verification:$('#r-verification').value,acceptance:$('#r-acceptance').value,dependsOn:$('#r-deps').value.split(',').map(x=>x.trim()).filter(Boolean)};if($('#r-key').value||$('#r-value').value)r.constraint={key:$('#r-key').value,value:$('#r-value').value};const exists=project.requirements.some(x=>x.id===r.id);if(exists&&!$('#r-id').readOnly)throw Error('ID already exists. Use Edit on that requirement.');changed(B.update(project,{requirements:exists?project.requirements.map(x=>x.id===r.id?r:x):[...project.requirements,r]}));e.target.reset();$('#r-id').readOnly=false})};
$('#clear-requirement').onclick=()=>{$('#requirement-form').reset();$('#r-id').readOnly=false};
$('#question-form').onsubmit=e=>{e.preventDefault();run(()=>{let n=1;while(project.questions.some(q=>q.id==='Q'+n))n++;changed(B.update(project,{questions:[...project.questions,{id:'Q'+n,text:$('#new-question').value,answer:''}]}));e.target.reset()})};
$('#save-answers').onclick=()=>run(()=>changed(B.update(project,{questions:project.questions.map(q=>({...q,answer:document.querySelector('[data-question="'+q.id+'"]').value}))})));
$('#approval').onclick=()=>run(()=>{project=B.approve(project,$('#approver').value);save();render();notice('Brief approved. You can now prepare an assignment.')});
$('#make-task').onclick=()=>run(()=>{pack=B.task(project,[...document.querySelectorAll('#task-picks input:checked')].map(i=>i.value),$('#objective').value);evidence=[];$('#task-preview').value=B.markdown(project,pack);$('#task-download').disabled=false;buildReview();notice('Task packet prepared. All hard project guardrails are included.')});
function buildReview(){const host=$('#review-rows');host.replaceChildren();for(const r of [...pack.requirements,...pack.guardrails]){const row=el('fieldset');row.dataset.id=r.id;row.append(el('legend',r.id+' · '+r.text),el('p',r.acceptance));for(const [key,title,type]of[['outcome','Outcome','select'],['note','What did you check?','textarea'],['reference','Evidence reference (file, URL or test record)','input'],['reviewer','Who reviewed it?','input']]){const l=el('label',title),i=el(type);i.dataset.field=key;if(type==='select'){for(const [v,t]of[['unknown','Unverified'],['met','Reviewer says met'],['failed','Conflict found']]){const o=el('option',t);o.value=v;i.append(o)}}else i.maxLength=key==='reviewer'?160:4000;l.append(i);row.append(l)}host.append(row)}$('#review-result').textContent='No evidence recorded yet.'}
$('#review').onclick=()=>run(()=>{if(!pack)throw Error('Prepare a task first.');evidence=[...document.querySelectorAll('#review-rows fieldset')].filter(row=>row.querySelector('select').value!=='unknown').map(row=>{const e={id:row.dataset.id};for(const input of row.querySelectorAll('[data-field]'))e[input.dataset.field]=input.value;return e});const result=B.review(project,pack,evidence);$('#review-result').textContent=result.counts.attested+' reviewer-attested · '+result.counts.conflict+' conflicts · '+result.counts.unverified+' unverified. '+result.disclaimer});
function download(name,value,type){const u=URL.createObjectURL(new Blob([value],{type})),a=el('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);notice('Download requested. Keep the JSON file to reopen your brief.')}
$('#download').onclick=()=>run(()=>download('proofroom-brief.json',JSON.stringify(project,null,2),'application/json'));
$('#master').onclick=()=>run(()=>download('MASTER.md',B.markdown(project),'text/markdown'));
$('#task-download').onclick=()=>run(()=>download('TASK.md',B.markdown(project,pack),'text/markdown'));
$('#import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>1000000)throw Error('File exceeds 1 MB');const imported=B.parse(await f.text());if(!confirm('Replace the current brief? Download it first if you want to keep it.'))return;project=imported;pack=null;evidence=[];save();render();notice('Brief imported. Approval reflects its exact saved contents.')}catch(err){notice(err.message)}finally{e.target.value=''}};
$('#new').onclick=()=>{if(!confirm('Start a new brief? Download the current one first to keep it.'))return;changed({version:1,name:'Untitled product',goal:'Describe the outcome you want.',audience:'Describe your first user.',requirements:[],questions:[{id:'Q1',text:'What is explicitly outside the first release?',answer:''},{id:'Q2',text:'What observable result would count as success?',answer:''}]})};
render();
